baseURL = 'https://sisakulint.github.io'
languageCode = 'en-us'
title = 'sisakulint Document'
publishDir = './public'
enableGitInfo = true

[param]
BookRepo = 'https://sisakulint.github.io'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'
